package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"
	"fmt"
	"log"
	"math"
	"validation/graph/model"
)

// VerifyTenantTable is the resolver for the VerifyTenantTable field.
func (r *mutationResolver) VerifyTenantTable(ctx context.Context, input model.VerifyTenantTable) (bool, error) {
	log.Println("rreq cacmee")
	err, match := r.TableRow.VerifyTenantTable(&ctx, &input)
	if err != nil {
		log.Printf("faile to verify %v\n", err)
		return match, err
	}
	return match, nil
}

// InsertTenantUserRow is the resolver for the InsertTenantUserRow field.
func (r *mutationResolver) InsertTenantUserRow(ctx context.Context, input model.InsertTenantUserRow) (int32, error) {
	log.Println("rreq cacmee")
	row_id, err := r.TableRow.InsertTenantUserRow(&ctx, &input)
	if err != nil {
		return -1, err
	}

	if row_id > math.MaxInt32 || row_id < math.MinInt32 {
		panic("overflow")
	}

	rowId := int32(row_id)
	return rowId, nil
}

// ReadTenantUserRow is the resolver for the ReadTenantUserRow field.
func (r *mutationResolver) ReadTenantUserRow(ctx context.Context, input model.ReadTenantUserRow) ([]*model.TableRow, error) {
	log.Println("rreq cacmee")
	rows, err := r.TableRow.ReadTenantUserRow(&ctx, &input)
	if err != nil {

		return nil, err
	}
	return rows, nil
}

// UpdateTenantUserRow is the resolver for the UpdateTenantUserRow field.
func (r *mutationResolver) UpdateTenantUserRow(ctx context.Context, input model.UpdateTenantUserRow) (*model.TableRow, error) {
	log.Println("rreq cacmee")
	row, err := r.TableRow.UpdateTenantUserRow(&ctx, &input)
	if err != nil {

		return nil, err
	}
	return row, nil
}

// Signin is the resolver for the Signin field.
func (r *mutationResolver) Signin(ctx context.Context, input model.Signin) (*model.Token, error) {
	log.Println("rreq cacmee")
	panic(fmt.Errorf("not implemented: Signin - Signin"))
}

// Signup is the resolver for the Signup field.
func (r *mutationResolver) Signup(ctx context.Context, input model.Signup) (bool, error) {
	log.Println("rreq cacmee")
	panic(fmt.Errorf("not implemented: Signup - Signup"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
