// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type InsertTenantUserRow struct {
	UserID         uuid.UUID `json:"user_Id"`
	TenantUserUUID string    `json:"tenant_user_uuid"`
	Rows           []*Row    `json:"rows"`
}

type Mutation struct {
}

type Pathidk struct {
	Path  []string `json:"Path,omitempty"`
	Value *string  `json:"Value,omitempty"`
}

type Query struct {
}

type ReadTenantUserRow struct {
	UserID         uuid.UUID `json:"user_Id"`
	TenantUserUUID string    `json:"tenant_user_uuid"`
	TableID        uuid.UUID `json:"table_Id"`
	TableName      string    `json:"table_name"`
}

type Row struct {
	TableID   uuid.UUID      `json:"table_Id"`
	TableName string         `json:"table_name"`
	Data      map[string]any `json:"data"`
}

type Signin struct {
	TableName *string `json:"table_name,omitempty"`
	TableID   *string `json:"table_id,omitempty"`
	Username  *string `json:"username,omitempty"`
	Mail      *string `json:"mail,omitempty"`
	Pass      *string `json:"pass,omitempty"`
}

type Signup struct {
	TableName *string `json:"table_name,omitempty"`
	TableID   *string `json:"table_id,omitempty"`
	Username  *string `json:"username,omitempty"`
	Mail      *string `json:"mail,omitempty"`
	Pass      *string `json:"pass,omitempty"`
}

type UpdateTenantUserRow struct {
	UserID         uuid.UUID      `json:"user_Id"`
	TenantUserUUID string         `json:"tenant_user_uuid"`
	TableID        uuid.UUID      `json:"table_Id"`
	TableName      string         `json:"table_name"`
	Data           map[string]any `json:"data,omitempty"`
	RowID          int32          `json:"row_id"`
	Path           []*Pathidk     `json:"path"`
}

type User struct {
	ID                   *string    `json:"id,omitempty"`
	UserID               *uuid.UUID `json:"user_id,omitempty"`
	UserName             *string    `json:"user_name,omitempty"`
	PassWord             *string    `json:"pass_word,omitempty"`
	Email                *string    `json:"email,omitempty"`
	IsActive             *bool      `json:"is_active,omitempty"`
	RefreshToke          *string    `json:"refresh_toke,omitempty"`
	AccessToken          *string    `json:"access_token,omitempty"`
	ReadOnlyRefreshToken *string    `json:"read_only_refresh_token,omitempty"`
	UpdatedAt            *time.Time `json:"updated_at,omitempty"`
	CreatedAt            *time.Time `json:"created_at,omitempty"`
}

type VerifyTenantTable struct {
	UserID     uuid.UUID  `json:"user_Id"`
	TableID    *uuid.UUID `json:"table_Id,omitempty"`
	TableName  *string    `json:"table_name,omitempty"`
	ColumnName *string    `json:"column_name,omitempty"`
}

type TableRow struct {
	ID   *string        `json:"id,omitempty"`
	Data map[string]any `json:"data,omitempty"`
}

type Token struct {
	AccessToken  *string `json:"access_token,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
}

type UsersTables struct {
	UserID    *uuid.UUID `json:"user_id,omitempty"`
	TableID   *uuid.UUID `json:"table_id,omitempty"`
	TableName *string    `json:"table_name,omitempty"`
}
