version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    env_file:
      - .env

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "${REDIS_INSIGHT_PORT}:5540"
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  redis_data: